spring.application.name=eatsmeet

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET}


#INSERT INTO employees (
#active, address, bod, contact, email, img_url, name, nic, password, refresh_token, role
#) VALUES (
#0x01,                     -- active
#'Kandy, Sri Lanka',       -- address
#NULL,                     -- bod (birthday)
#'0779876543',             -- contact
#'admin@gmail.com',      -- email
#NULL,                     -- img_url
#'Rohan Perera',           -- name
#'982345999V',             -- nic
#'$2a$12$CFtl5iFUWNUFOs8sLsQ/fuUUjU.7eMsJcIosZLVJCpf130AbArfUq', -- password (bcrypt hash format)
#NULL,                     -- refresh_token
#'ADMIN'               -- role
#);